#!/usr/bin/env bash
# Canonical parity verification. Pin a commit, build from a pristine worktree,
# run the standard arm set with the correct environment, print a fixed report.
#
# SLOT SEMANTICS (measured by this script): MAX_SLOTS bounds the attacks the
# device holds CONCURRENTLY, not the number of allocations it has ever made - a
# position is reused the moment its attack dies. The report line
#   "slot positions allocated N of a ceiling of 1024 CONCURRENT attacks"
# must therefore show N equal to the record's PEAK concurrent attack count
# (pangaea N=488 t500: 488, reached at boundary 79), while the record's
# CUMULATIVE attack births over boundaries 2..500 are 1191. Before the slot-reuse
# fix the append-only allocator burned those 1024 positions cumulatively and
# REFUSED at boundary 435 (freeze arms, self-drive origination) and 438 (plain
# replay, new attack) - a harness capacity limit, not a divergence - which is why
# the arm set used to stop at 434 and why the old default TICKS was 434.
#
# DUMPS: $O must have been generated by the ORACLE WITH THE FINAL-BOUNDARY FIX.
# A fresh dump used to carry ZERO ATTACK rows at its own final boundary (the
# oracle skipped emit_attacks when b == ticks), so at a cell's final boundary the
# device's whole live list looked like extra attacks and pc_create/pc_evict/
# pc_troops there were unreadable as agreement evidence. Verify with:
#   grep -c "^ATTACK 434 " $O/pangaea_n488_nat0_t434.dump   # now 149, matches t500
set -u
S=/opt/data/workspaces/skg
M=$S/ofcuda_matrix
O=$M/out/matrix/oracle; RF=$M/out/matrix/refs
REF=${1:?usage: verify_parity.sh <commit> [ticks_for_long_arms]}
TICKS=${2:-500}
OUT=${OUT:-/tmp/parity-vb}; rm -rf $OUT; mkdir -p $OUT
export PATH=/nix/store/qmdxxa88bgbdx31dav3qlssb4rghr14c-gcc-wrapper-14.4.0/bin:$PATH
export LD_LIBRARY_PATH=/run/opengl-driver/lib
export CARGO_TARGET_DIR=$S/.target-parity-verify
cd /tmp/lgr-wt || { echo NO_WORKTREE; exit 1; }
git checkout -q --detach "$REF" || { echo PIN_FAIL; exit 1; }
echo "pinned $(git rev-parse --short HEAD) dirty=$(git status --porcelain | wc -l)"
W=/tmp/lgr-wt/cuda/ofcuda_matrix
cd $W || exit 1
if nice -n 10 bash $S/ofcuda_env.sh cargo oxide build -- --release --bin ofcuda_matrix > $OUT/build.log 2>&1; then echo "BUILD OK ptx_fma=$(grep -c fma.rn.f64 $W/ofcuda_matrix.ptx)"; else echo BUILD_FAIL; tail -5 $OUT/build.log; exit 1; fi
BIN=$CARGO_TARGET_DIR/release/ofcuda_matrix
run(){ tag=$1; ticks=$2; shift 2; s=$SECONDS; env "$@" "$BIN" --map pangaea --agents 488 --nations 0 --ticks $ticks --oracle-dir $O --refs-dir $RF --out $OUT/$tag > $OUT/$tag.log 2>&1; echo "[$tag] $((SECONDS-s))s rc=$?"; }
run freeze20 $TICKS OFCUDA_MATRIX_FREEZE_ATTACKS=20
run freeze60 $TICKS OFCUDA_MATRIX_FREEZE_ATTACKS=60
run freeze20_full 500 OFCUDA_MATRIX_FREEZE_ATTACKS=20
run freeze60_full 500 OFCUDA_MATRIX_FREEZE_ATTACKS=60
run plain500 500
run plain437 437
run t250 250
for t in freeze20 freeze60 plain500 plain437 t250; do
  f=$(ls $OUT/$t/pangaea_n488_nat0_*/result.txt 2>/dev/null | head -1)
  echo "=== $t"
  if [ -n "$f" ]; then grep -aE "slot positions allocated|hash matched|troops matched|first divergence|SELFDRIVE totals" "$f" | head -5; else echo "  VOID: no result file"; fi
done
echo "=== the pre-fix 1024-slot capacity wall must be GONE at every tick (no refusal line anywhere)"
grep -aE "CELL FAILED|MAX_SLOTS|more than 1024" $OUT/*.log | head -4
echo "=== both freeze arms over the full 500-boundary record: hash/troops exact, first divergence none"
for t in freeze20_full freeze60_full; do
  f=$(ls $OUT/$t/pangaea_n488_nat0_*/result.txt 2>/dev/null | head -1)
  echo "== $t"
  if [ -n "$f" ]; then grep -aE "hash matched|owned counts matched|troops matched|first divergence" "$f" | head -4; else echo "  VOID: no result file"; fi
done
s=$SECONDS; $BIN --cells-file $W/tools/cells_mx30_t60.txt --oracle-dir $O --refs-dir $RF --out $OUT/mx > $OUT/mx.log 2>&1; echo "[mx30] $((SECONDS-s))s"; grep -aE "cells: [0-9]+ passed" $OUT/mx.log
echo PARITYVERIFYDONE
