#!/usr/bin/env bash
# Sets up a local libtorch for `tch` (oftrain) on macOS, where prebuilt
# libtorch binaries aren't published and `download-libtorch` can't work.
# Installs a pinned pip torch into rust/.libtorch-venv (matching the
# TORCH_VERSION that tch-rs 0.24.x's torch-sys expects) and writes
# rust/.cargo/config.toml so `cargo build`/`run` pick it up automatically.
#
# On the CUDA training pod, prefer LIBTORCH_USE_PYTORCH=1 against the
# pod's existing torch install, or the `download-libtorch` feature with
# TORCH_CUDA_VERSION set - this script is a macOS-only dev convenience.
set -euo pipefail

TORCH_VERSION="2.11.0"
RUST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$RUST_DIR/.libtorch-venv"

if [ ! -d "$VENV" ]; then
  python3 -m venv "$VENV"
fi
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet "torch==$TORCH_VERSION"

LIBTORCH="$("$VENV/bin/python" -c 'import torch, pathlib; print(pathlib.Path(torch.__file__).parent)')"

mkdir -p "$RUST_DIR/.cargo"
cat > "$RUST_DIR/.cargo/config.toml" <<EOF
# Auto-generated by scripts/setup_libtorch.sh. Do not commit (gitignored).
[env]
LIBTORCH = "$LIBTORCH"
DYLD_LIBRARY_PATH = "$LIBTORCH/lib"
EOF

echo "libtorch ready at $LIBTORCH"
echo "wrote $RUST_DIR/.cargo/config.toml"
