#!/usr/bin/env python3
"""Drain local GameRecord spool into parquet shards on Hugging Face.

Usage:
  uv run --with pyarrow python scripts/hf_replay_upload.py
  uv run --with pyarrow python scripts/hf_replay_upload.py --spool /data/replay-spool --shard-size 1000

Env:
  HF_TOKEN          write token (required unless --dry-run)
  DATA_DIR          default spool parent (/data or .)
  HF_REPLAYS_REPO   default djmango/openfront-replays
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from thinking_compact import load_thinking_for_record  # noqa: E402

DATASET_REPO = os.environ.get("HF_REPLAYS_REPO", "djmango/openfront-replays")

DATASET_CARD = """---
license: mit
pretty_name: OpenFront.io RL GameRecords
tags:
  - reinforcement-learning
  - games
  - openfront
---

# OpenFront.io RL game replays

Sparse-turn **GameRecord v0.0.2** JSON for every finished RL episode
(training, watch, showcase). Same format as the OpenFront client archive /
Node bridge (`version`, `gitCommit`, sparse `turns` with intents).

Each parquet row is one game. The `record_json` column is the full Node-
compatible GameRecord string (~100–200 KB for long games). When a watch /
showcase episode recorded policy decisions, `thinking_json` holds a compact
top-3 action trace (typically a few KB) derived from the MODEL overlay
`.debug.json` sidecar. Metadata columns capture policy / engine / stage.

Generated by [djmango/openfront-ai](https://github.com/djmango/openfront-ai).
Replay with `datagen/replay.ts` or the client archive API / `ofshowcase archive`.
"""


def default_spool() -> Path:
    base = Path(os.environ.get("DATA_DIR", "."))
    return base / "replay-spool"


def list_ready(spool: Path) -> list[Path]:
    files = sorted(spool.glob("*.json"))
    skip_suffixes = (".meta.json", ".debug.json", ".thinking.json")
    return [
        p
        for p in files
        if not p.name.startswith("._") and not p.name.endswith(skip_suffixes)
    ]


def row_from_record(path: Path) -> dict:
    record = json.loads(path.read_text())
    meta_path = path.parent / f"{path.stem}.meta.json"
    meta = json.loads(meta_path.read_text()) if meta_path.is_file() else {}
    info = record.get("info") or {}
    winner = info.get("winner")
    thinking = load_thinking_for_record(path)
    return {
        "game_id": info.get("gameID") or meta.get("game_id") or path.stem,
        "map": (info.get("config") or {}).get("gameMap") or meta.get("map") or "",
        "num_turns": int(info.get("num_turns") or 0),
        "winner": json.dumps(winner) if winner is not None else "",
        "created_at": int(info.get("end") or meta.get("spooled_at") or 0),
        "git_commit": record.get("gitCommit") or "",
        "record_version": record.get("version") or "v0.0.2",
        "run_name": str(meta.get("run_name") or ""),
        "policy_update": str(meta.get("policy_update") or ""),
        "stage": int(meta.get("stage") if meta.get("stage") is not None else -1),
        "engine": str(meta.get("engine") or ""),
        "policy_repo": str(meta.get("policy_repo") or ""),
        "policy_revision": str(meta.get("policy_revision") or ""),
        "record_json": json.dumps(record, separators=(",", ":")),
        # Compact MODEL thinking (top-3 / stride). Empty when training spool
        # has no watch debug sidecar.
        "thinking_json": thinking,
    }


def next_shard_name(api, repo_id: str) -> str:
    try:
        files = api.list_repo_files(repo_id, repo_type="dataset")
    except Exception:
        files = []
    existing = [
        f
        for f in files
        if f.startswith("data/train-") and f.endswith(".parquet")
    ]
    n = 0
    for f in existing:
        stem = Path(f).stem  # train-000123
        try:
            n = max(n, int(stem.split("-", 1)[1]) + 1)
        except (IndexError, ValueError):
            continue
    return f"data/train-{n:06d}.parquet"


def pack_shard(rows: list[dict], out: Path) -> None:
    import pyarrow as pa
    import pyarrow.parquet as pq

    table = pa.Table.from_pylist(rows)
    out.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, out, compression="zstd")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spool", type=Path, default=None)
    ap.add_argument("--shard-size", type=int, default=1000)
    ap.add_argument("--repo", default=DATASET_REPO)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--min-files", type=int, default=1, help="skip if fewer ready records")
    ap.add_argument("--work-dir", type=Path, default=Path("/tmp/of-replay-shards"))
    args = ap.parse_args()

    spool = args.spool or default_spool()
    spool.mkdir(parents=True, exist_ok=True)
    ready = list_ready(spool)
    if len(ready) < args.min_files:
        print(f"spool {spool}: {len(ready)} ready (need {args.min_files}); nothing to do")
        return

    from huggingface_hub import HfApi

    token = os.environ.get("HF_TOKEN", "").strip()
    if not args.dry_run and not token:
        raise SystemExit("HF_TOKEN required (or pass --dry-run)")

    api = HfApi(token=token or None)
    if not args.dry_run:
        api.create_repo(args.repo, repo_type="dataset", exist_ok=True)
        # Ensure dataset card once.
        try:
            api.upload_file(
                path_or_fileobj=DATASET_CARD.encode(),
                path_in_repo="README.md",
                repo_id=args.repo,
                repo_type="dataset",
                commit_message="docs: replay dataset card",
            )
        except Exception as e:
            print(f"card upload note: {e}", flush=True)

    uploaded = 0
    while ready:
        batch = ready[: args.shard_size]
        ready = ready[args.shard_size :]
        rows = []
        consumed: list[Path] = []
        for path in batch:
            try:
                rows.append(row_from_record(path))
                consumed.append(path)
            except Exception as e:
                print(f"skip {path.name}: {e}", flush=True)
        if not rows:
            continue

        remote = next_shard_name(api, args.repo) if not args.dry_run else f"data/train-dryrun-{int(time.time())}.parquet"
        local = args.work_dir / Path(remote).name
        pack_shard(rows, local)
        print(
            f"packed {len(rows)} games -> {local} ({local.stat().st_size / 1e6:.1f} MB)",
            flush=True,
        )
        if args.dry_run:
            print(f"dry-run: would upload {remote}")
            continue

        api.upload_file(
            path_or_fileobj=str(local),
            path_in_repo=remote,
            repo_id=args.repo,
            repo_type="dataset",
            commit_message=f"add {len(rows)} GameRecords ({datetime.now(timezone.utc).isoformat()})",
        )
        print(f"uploaded https://huggingface.co/datasets/{args.repo}/blob/main/{remote}", flush=True)
        for path in consumed:
            stem = path.stem
            path.unlink(missing_ok=True)
            (path.parent / f"{stem}.meta.json").unlink(missing_ok=True)
            (path.parent / f"{stem}.thinking.json").unlink(missing_ok=True)
            (path.parent / f"{stem}.debug.json").unlink(missing_ok=True)
        uploaded += len(rows)
        local.unlink(missing_ok=True)

    print(f"done: {uploaded} games -> {args.repo}")


if __name__ == "__main__":
    main()
