"""Upload dataset tars and model checkpoint to Hugging Face.

Usage:
  python scripts/hf_upload.py dataset        # uploads hf-dataset/*.tar
  python scripts/hf_upload.py model          # uploads runs/ae_v1/ae.pt + card
  python scripts/hf_upload.py human-dataset  # uploads hf-human/*.tar + records
"""

import sys
from pathlib import Path

from huggingface_hub import HfApi

DATASET_REPO = "djmango/openfront-snapshots"
HUMAN_DATASET_REPO = "djmango/openfront-human-games"
MODEL_REPO = "djmango/openfront-tile-autoencoder"

DATASET_CARD = """---
license: mit
pretty_name: OpenFront.io game-state snapshots
tags:
  - reinforcement-learning
  - games
---

# OpenFront.io game-state snapshots

250 bot/nation-only games of [OpenFront.io](https://openfront.io) (25 games on
each of 10 maps), played headless on the real deterministic game engine
([openfrontio/OpenFrontIO](https://github.com/openfrontio/OpenFrontIO)) and
snapshotted every 10 ticks / 1s of game time (~375k snapshots total).

Generated by and documented at
**[github.com/djmango/openfront-ai](https://github.com/djmango/openfront-ai)** -
see the repo for loaders, training code, and results.

**Format v3**: every snapshot captures the *complete* game state - the tile
grid plus all entities (players, diplomacy, units, attacks in flight) - so a
single snapshot is enough to reconstruct everything an agent could observe.
The 10-tick cadence means a typical nuke flight (20-60 ticks) spans 2-6
snapshots, and units in transit carry their destination.

One tar per map. Each game directory contains:

- `terrain.bin` - uint8[w*h] immutable terrain (bit 7 land, bit 6 shoreline,
  bit 5 ocean, bits 0-4 magnitude; magnitude 31 = impassable)
- `states/t<tick>.bin.gz` - gzipped little-endian uint16[w*h] mutable tile
  state: owner smallID in bits 0-11 (0 = unowned), fallout bit 13, defense
  bonus bit 14
- `states/t<tick>.json.gz` - gzipped JSON with full entity state:
  - `players`: id (smallID), name, type, troops, gold, tiles, alive, traitor,
    disconnected, targets, embargoes, pending alliance requests (in/out),
    sparse relation list
  - `alliances`: `[playerA, playerB, expiresAtTick]` for each active alliance
  - `units`: type (city, port, warship, transport, silo, SAM, nukes in
    flight, ...), owner, x, y, target tile tx/ty (null if idle - for nukes
    this is the impact point), samLock (a SAM is intercepting), level,
    health, constructing, cooldown, troops
  - `attacks`: from, to (0 = terra nullius), troops, retreating, srcX/srcY
    (boat-landing origin, null for land attacks)
- `meta.json` - format version, map, dims, snapshot tick list, winner

A game evolving (each color a player, Onion map, ticks 3175 and 12375):

![mid game](preview_mid.png) ![late game](preview_late.png)

Generated by [djmango/openfront-ai](https://github.com/djmango/openfront-ai)
for training observation encoders for RL agents.
"""

HUMAN_DATASET_CARD = """---
license: mit
pretty_name: OpenFront.io archived human games
tags:
  - reinforcement-learning
  - imitation-learning
  - games
---

# OpenFront.io archived human games

285 real public multiplayer games of [OpenFront.io](https://openfront.io)
(10-116 humans per lobby, all maps, FFA + team modes), pulled from the
game's public archive API and replayed through the deterministic engine
([openfrontio/OpenFrontIO](https://github.com/openfrontio/OpenFrontIO)) to
regenerate full state trajectories. ~420k snapshots at 10-tick (1s) cadence.

Every game passed the engine's embedded state-hash verification during
replay (games that desynced were discarded), so snapshots are bit-exact
reconstructions of what the players actually saw. Player identities are
stripped by the API; usernames remain.

Generated by and documented at
**[github.com/djmango/openfront-ai](https://github.com/djmango/openfront-ai)**.

## Contents

- `maps/<map>.tar` - replayed snapshots, one game directory per game, same
  format v3 as [openfront-snapshots](https://huggingface.co/datasets/djmango/openfront-snapshots):
  `terrain.bin`, `states/t<tick>.bin.gz` (tile ownership grid),
  `states/t<tick>.json.gz` (players, diplomacy, units, attacks),
  `meta.json` (+ `gitCommit`, `hashesChecked`, `numHumans`).
- `records/<gitCommit>/<gameID>.json.gz` - the raw archived game records:
  full per-turn **human intent logs** (every attack, boat, build, nuke,
  alliance, betrayal, donation, emote). Replay them with
  `datagen/replay.ts` from the repo (engine checked out at the matching
  commit), or use them directly for behavior cloning.

## Why

Bot self-play data ([openfront-snapshots](https://huggingface.co/datasets/djmango/openfront-snapshots))
covers the state space thinly: built-in nations rarely ally, betray, nuke,
or invade by sea. Human games supply realistic territory shapes and the
full diplomatic/military action distribution - both better observation
coverage for encoders and (state, human action) pairs for imitation
pretraining.
"""

MODEL_CARD = """---
license: mit
tags:
  - reinforcement-learning
  - autoencoder
  - games
---

# OpenFront spatial autoencoder

Frozen spatial observation encoder for [OpenFront.io](https://openfront.io)
RL agents: compresses tile ownership + terrain + fallout + static structures
into a latent grid (any map size). Structure detection is at precision/recall
1.0 per class for every model below.

**Current best: `ae_v31_d8.pt`** - v3.1 architecture (terrain-conditioned
nearest-upsample decoder, focal loss, border-dense sampling, cosine LR) with
the latent at 1/8 resolution instead of 1/16. Trained 40k steps on a mixed
corpus of bot self-play and real archived human games.

Border-tile accuracy (the hard metric - overall tile accuracy saturates at
~99% for all models), uniform 256-crop eval:

| checkpoint | latent | human border | bot border | human tiles | bot tiles |
|---|---|---|---|---|---|
| `ae_v31_d8.pt` | 64ch @ 1/8 | **89.3%** | **96.1%** | 99.6% | 99.8% |
| `ae_v31.pt` | 64ch @ 1/16 | 78.5% | 90.7% | 99.1% | 99.6% |
| `ae_v3.pt` (bot-only) | 64ch @ 1/16 | 71.8% | 87.5% | 99.2% | 99.4% |

The ablation story: mixing human games into training fixes the human-domain
gap, the v3.1 decoder/loss fixes add a few points, and latent *resolution*
(not channel count) is what finally cracks border geometry - borders are
high-frequency spatial detail that can't be bought back with more channels.

Full details, training code, results, and roadmap:
**[github.com/djmango/openfront-ai](https://github.com/djmango/openfront-ai)**

![reconstruction](recon_v3_world.png)

Trained on
[djmango/openfront-snapshots](https://huggingface.co/datasets/djmango/openfront-snapshots)
(bot) and
[djmango/openfront-human-games](https://huggingface.co/datasets/djmango/openfront-human-games)
(human).

```python
import torch
from ae.model_v3 import SpatialAE

ckpt = torch.load("ae_v31_d8.pt", map_location="cpu", weights_only=False)
a = ckpt["args"]
model = SpatialAE(
    latent_c=a["latent_c"],
    terrain_cond=a.get("terrain_cond", False),
    upsample_decoder=a.get("upsample_decoder", False),
    latent_down=a.get("latent_down", 16),
)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()
z = model.encode(owner_slots, terrain, static_planes)  # (B, 64, H/8, W/8)
```

`ae.pt` (v1 tile-only `TileAutoencoder` in `model.py`) is kept for history.
"""


def main() -> None:
    what = sys.argv[1]
    api = HfApi()

    if what == "dataset":
        api.create_repo(DATASET_REPO, repo_type="dataset", exist_ok=True)
        api.upload_file(
            path_or_fileobj=DATASET_CARD.encode(),
            path_in_repo="README.md",
            repo_id=DATASET_REPO,
            repo_type="dataset",
        )
        for tar in sorted(Path("hf-dataset").glob("*.tar")):
            print(f"uploading {tar.name} ...", flush=True)
            api.upload_file(
                path_or_fileobj=tar,
                path_in_repo=f"maps/{tar.name}",
                repo_id=DATASET_REPO,
                repo_type="dataset",
            )
        print(f"done: https://huggingface.co/datasets/{DATASET_REPO}")

    elif what == "model":
        api.create_repo(MODEL_REPO, exist_ok=True)
        api.upload_file(
            path_or_fileobj=MODEL_CARD.encode(),
            path_in_repo="README.md",
            repo_id=MODEL_REPO,
        )
        for src, dst in [
            ("runs/ae_v31_d8/ae_v3.pt", "ae_v31_d8.pt"),
            ("runs/ae_v31/ae_v3.pt", "ae_v31.pt"),
            ("runs/ae_v3/ae_v3.pt", "ae_v3.pt"),
            ("ae/model_v3.py", "model_v3.py"),
            ("ae/units.py", "units.py"),
            ("assets/loss_curve_v3.png", "loss_curve_v3.png"),
            ("assets/recon_v3_world.png", "recon_v3_world.png"),
        ]:
            api.upload_file(path_or_fileobj=src, path_in_repo=dst, repo_id=MODEL_REPO)
        print(f"done: https://huggingface.co/{MODEL_REPO}")

    elif what == "human-dataset":
        api.create_repo(HUMAN_DATASET_REPO, repo_type="dataset", exist_ok=True)
        api.upload_file(
            path_or_fileobj=HUMAN_DATASET_CARD.encode(),
            path_in_repo="README.md",
            repo_id=HUMAN_DATASET_REPO,
            repo_type="dataset",
        )
        print("uploading records ...", flush=True)
        api.upload_folder(
            folder_path="records",
            path_in_repo="records",
            repo_id=HUMAN_DATASET_REPO,
            repo_type="dataset",
        )
        for tar in sorted(Path("hf-human").glob("*.tar")):
            print(f"uploading {tar.name} ...", flush=True)
            api.upload_file(
                path_or_fileobj=tar,
                path_in_repo=f"maps/{tar.name}",
                repo_id=HUMAN_DATASET_REPO,
                repo_type="dataset",
            )
        print(f"done: https://huggingface.co/datasets/{HUMAN_DATASET_REPO}")

    elif what == "bc-sidecars":
        # Behavior-cloning supervision (datagen/replay.ts --bc): one tar of
        # every data-human/<map>/<game>/bc.json.gz, paths relative to
        # data-human so it extracts over the map tars.
        import tarfile

        out = Path("bc-sidecars.tar")
        with tarfile.open(out, "w") as t:
            for f in sorted(Path("data-human").glob("*/*/bc.json.gz")):
                t.add(f, arcname=str(f.relative_to("data-human")))
        print(f"packed {out} ({out.stat().st_size / 1e9:.2f} GB); uploading ...")
        api.upload_file(
            path_or_fileobj=out,
            path_in_repo="bc/bc-sidecars.tar",
            repo_id=HUMAN_DATASET_REPO,
            repo_type="dataset",
        )
        print(f"done: https://huggingface.co/datasets/{HUMAN_DATASET_REPO}")

    elif what == "dataset-card":
        api.upload_file(
            path_or_fileobj=DATASET_CARD.encode(),
            path_in_repo="README.md",
            repo_id=DATASET_REPO,
            repo_type="dataset",
        )
        for src, dst in [
            ("data/onion/onion-7-0/preview/tick_003175.png", "preview_mid.png"),
            ("data/onion/onion-7-0/preview/tick_012375.png", "preview_late.png"),
        ]:
            api.upload_file(
                path_or_fileobj=src,
                path_in_repo=dst,
                repo_id=DATASET_REPO,
                repo_type="dataset",
            )
        print(f"card updated: https://huggingface.co/datasets/{DATASET_REPO}")

    else:
        raise SystemExit(
            "usage: hf_upload.py dataset|model|dataset-card|human-dataset|bc-sidecars"
        )


if __name__ == "__main__":
    main()
