"""Upload dataset tars and model checkpoint to Hugging Face.

Usage:
  python scripts/hf_upload.py dataset   # uploads hf-dataset/*.tar
  python scripts/hf_upload.py model     # uploads runs/ae_v1/ae.pt + card
"""

import sys
from pathlib import Path

from huggingface_hub import HfApi

DATASET_REPO = "djmango/openfront-snapshots"
MODEL_REPO = "djmango/openfront-tile-autoencoder"

DATASET_CARD = """---
license: mit
pretty_name: OpenFront.io game-state snapshots
tags:
  - reinforcement-learning
  - games
---

# OpenFront.io game-state snapshots

250 bot/nation-only games of [OpenFront.io](https://openfront.io) (25 games on
each of 10 maps), played headless on the real deterministic game engine
([openfrontio/OpenFrontIO](https://github.com/openfrontio/OpenFrontIO)) and
snapshotted every 25 ticks.

One tar per map. Each game directory contains:

- `terrain.bin` — uint8[w*h] immutable terrain (bit 7 land, bit 6 shoreline,
  bit 5 ocean, bits 0-4 magnitude; magnitude 31 = impassable)
- `states/t<tick>.bin.gz` — gzipped little-endian uint16[w*h] mutable tile
  state: owner smallID in bits 0-11 (0 = unowned), fallout bit 13, defense
  bonus bit 14
- `meta.json` — dims, snapshot tick list, per-snapshot per-player stats
  (troops, gold, tiles, alive), winner

Generated by [djmango/openfront-ae](https://github.com/djmango/openfront-ae)
for training observation encoders for RL agents.
"""

MODEL_CARD = """---
license: mit
tags:
  - reinforcement-learning
  - autoencoder
  - games
---

# OpenFront tile-state autoencoder

Fully-convolutional autoencoder over [OpenFront.io](https://openfront.io)
tile-ownership state, intended as a frozen spatial observation encoder for RL
agents. 64x compression: 16x16 spatial downsampling into 64 latent channels
per region, works on any map size.

- Input: per-tile owner slot (static per-game slot assignment, 8-dim learned
  embedding) + terrain channels (land, magnitude, fallout)
- Loss: border-weighted cross-entropy reconstruction of owner slots
- Trained on [djmango/openfront-snapshots](https://huggingface.co/datasets/djmango/openfront-snapshots)
  (250 games, 10 maps, random 256x256 crops)

Training code and usage: [djmango/openfront-ae](https://github.com/djmango/openfront-ae)

```python
import torch
from ae.model import TileAutoencoder

ckpt = torch.load("ae.pt", map_location="cpu", weights_only=False)
model = TileAutoencoder(latent_c=ckpt["args"]["latent_c"])
model.load_state_dict(ckpt["model_state_dict"])
model.eval()
z = model.encode(owner_slots, terrain)  # (B, 64, H/16, W/16)
```
"""


def main() -> None:
    what = sys.argv[1]
    api = HfApi()

    if what == "dataset":
        api.create_repo(DATASET_REPO, repo_type="dataset", exist_ok=True)
        api.upload_file(
            path_or_fileobj=DATASET_CARD.encode(),
            path_in_repo="README.md",
            repo_id=DATASET_REPO,
            repo_type="dataset",
        )
        for tar in sorted(Path("hf-dataset").glob("*.tar")):
            print(f"uploading {tar.name} ...", flush=True)
            api.upload_file(
                path_or_fileobj=tar,
                path_in_repo=f"maps/{tar.name}",
                repo_id=DATASET_REPO,
                repo_type="dataset",
            )
        print(f"done: https://huggingface.co/datasets/{DATASET_REPO}")

    elif what == "model":
        api.create_repo(MODEL_REPO, exist_ok=True)
        api.upload_file(
            path_or_fileobj=MODEL_CARD.encode(),
            path_in_repo="README.md",
            repo_id=MODEL_REPO,
        )
        api.upload_file(
            path_or_fileobj="runs/ae_v1/ae.pt",
            path_in_repo="ae.pt",
            repo_id=MODEL_REPO,
        )
        api.upload_file(
            path_or_fileobj="ae/model.py",
            path_in_repo="model.py",
            repo_id=MODEL_REPO,
        )
        print(f"done: https://huggingface.co/{MODEL_REPO}")

    else:
        raise SystemExit("usage: hf_upload.py dataset|model")


if __name__ == "__main__":
    main()
