//! Tribe bot spawner (`execution/TribeSpawner.ts`).

use crate::execution::spawn::SpawnExecution;
use crate::game::{PlayerInfo, PlayerType};
use crate::prng::PseudoRandom;
use crate::util::simple_hash;

/// Must stay byte-for-byte identical (same order) to TS `TRIBE_NAME_PREFIXES`
/// in `execution/utils/TribeNames.ts` - `simpleHash(name)` of the assembled
/// tribe name feeds hash-based scheduling (e.g. cluster-removal cadence), so
/// any mismatch here desyncs bot behavior even though RNG draw counts match.
const PREFIXES: &[&str] = &[
    "Akkadian",
    "Babylonian",
    "Sumerian",
    "Hittite",
    "Phoenician",
    "Canaanite",
    "Minoan",
    "Mycenaean",
    "Etruscan",
    "Scythian",
    "Thracian",
    "Dacian",
    "Illyrian",
    "Median",
    "Chaldean",
    "Roman",
    "Greek",
    "Byzantine",
    "Persian",
    "Parthian",
    "Seleucid",
    "Ptolemaic",
    "Palmyrene",
    "Macedonian",
    "Carthaginian",
    "Ming",
    "Tang",
    "Song",
    "Yuan",
    "Mauryan",
    "Kushan",
    "Rajput",
    "Mughal",
    "Satavahana",
    "Vijayanagara",
    "Egyptian",
    "Nubian",
    "Kushite",
    "Aksumite",
    "Ethiopian",
    "Songhai",
    "Malian",
    "Ghanaian",
    "Benin",
    "Ashanti",
    "Zulu",
    "Tuareg",
    "Berber",
    "Kanem-Bornu",
    "Buganda",
    "Mossi",
    "Swahili",
    "Somali",
    "Wolof",
    "Umayyad",
    "Abbasid",
    "Ayyubid",
    "Fatimid",
    "Mamluk",
    "Seljuk",
    "Safavid",
    "Ottoman",
    "Almoravid",
    "Almohad",
    "Rashidun",
    "Ziyarid",
    "Frankish",
    "Visigothic",
    "Ostrogothic",
    "Viking",
    "Norman",
    "Saxon",
    "Anglo-Saxon",
    "Celtic",
    "Gaulish",
    "Carolingian",
    "Merovingian",
    "Capetian",
    "Plantagenet",
    "Tudor",
    "Stuart",
    "Habsburg",
    "Romanov",
    "Lancaster",
    "York",
    "Bourbon",
    "Napoleonic",
    "British",
    "French",
    "Spanish",
    "Portuguese",
    "Dutch",
    "Russian",
    "German",
    "Italian",
    "Swedish",
    "Norwegian",
    "Danish",
    "Polish",
    "Hungarian",
    "Austrian",
    "Swiss",
    "Czech",
    "Slovak",
    "Serbian",
    "Croatian",
    "Bosnian",
    "Montenegrin",
    "Bulgarian",
    "Romanian",
    "Apache",
    "Sioux",
    "Cherokee",
    "Navajo",
    "Iroquois",
    "Inuit",
    "Arawak",
    "Carib",
    "Taino",
    "Aztec",
    "Mayan",
    "Incan",
    "Mapuche",
    "Guarani",
    "Tupi",
    "Yanomami",
    "Zuni",
    "Hopi",
    "Kiowa",
    "Comanche",
    "Shoshone",
    "Japanese",
    "Ryukyu",
    "Ainu",
    "Cham",
    "Khmer",
    "Thai",
    "Vietnamese",
    "Burmese",
    "Balinese",
    "Malay",
    "Filipino",
    "Mongolian",
    "Korean",
    "Tibetan",
    "Manchu",
    "Uyghur",
    "Hmong",
    "Karen",
    "Pyu",
    "Hawaiian",
    "Fijian",
    "Tongan",
    "Samoan",
    "Maori",
    "Micronesian",
    "Hebrew",
    "Armenian",
    "Circassian",
    "Georgian",
    "Kurdish",
    "Turkic",
    "Kazakh",
    "Uzbek",
    "Kyrgyz",
    "Tajik",
    "Uighur",
    "Pashtun",
    "Baloch",
    "Afghan",
    "Kenyan",
    "Ugandan",
    "Bhutanese",
    "Latin",
    "Moldovan",
    "Militant",
    "Spartan",
];
const SUFFIXES: &[&str] = &[
    "Empire",
    "Dynasty",
    "Kingdom",
    "Queendom",
    "Sultanate",
    "Confederation",
    "Union",
    "Republic",
    "Caliphate",
    "Dominion",
    "Realm",
    "State",
    "Federation",
    "Territory",
    "Commonwealth",
    "League",
    "Duchy",
    "Province",
    "Protectorate",
    "Colony",
    "Mandate",
    "Free State",
    "Canton",
    "Region",
    "Nation",
    "Assembly",
    "Hierarchy",
    "Archduchy",
    "Grand Duchy",
    "Metropolis",
    "Cluster",
    "Alliance",
    "Tribunal",
    "Council",
    "Confederacy",
    "Order",
    "Regime",
    "Syndicate",
    "Guild",
    "Corporation",
    "Patriarchy",
    "Matriarchy",
    "Legion",
    "Horde",
    "Clan",
    "Brotherhood",
    "Sisterhood",
    "Ascendancy",
    "Supremacy",
    "Tribe",
    "Republics",
    "Army",
    "Dictatorship",
    "Country",
    "Oligarchy",
    "Monkdom",
    "Throng",
    "Host",
    "Area",
    "District",
    "Fief",
    "Wilderness",
    "Settlement",
    "Parliament",
    "Anarchy",
    "Democracy",
    "Autocracy",
];

pub struct TribeSpawner {
    game_id: String,
    random: PseudoRandom,
}

impl TribeSpawner {
    pub fn new(game_id: &str) -> Self {
        Self {
            game_id: game_id.to_string(),
            random: PseudoRandom::new(simple_hash(game_id) + 2),
        }
    }

    pub fn spawn_tribes(&mut self, n: u32) -> Vec<SpawnExecution> {
        (0..n)
            .map(|_| {
                SpawnExecution::new(
                    self.game_id.clone(),
                    PlayerInfo {
                        name: self.random_tribe_name(),
                        player_type: PlayerType::Bot,
                        client_id: None,
                        id: self.random.next_id(),
                        clan_tag: None,
                        friends: Vec::new(),
                        team: None,
                    },
                    None,
                )
            })
            .collect()
    }

    fn random_tribe_name(&mut self) -> String {
        let p = PREFIXES[self.random.next_int(0, PREFIXES.len() as i32) as usize];
        let s = SUFFIXES[self.random.next_int(0, SUFFIXES.len() as i32) as usize];
        format!("{p} {s}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prng::PseudoRandom;
    use crate::util::simple_hash;

    #[test]
    fn first_tribe_ids_match_ts_jby2g() {
        let game_id = "jby2gMJF";
        let mut tribe_rng = PseudoRandom::new(simple_hash(game_id) + 2);
        let expected = ["s8ozfync", "czjwcp3e", "a2dspr0g"];
        for (i, want) in expected.iter().enumerate() {
            tribe_rng.next_int(0, PREFIXES.len() as i32);
            tribe_rng.next_int(0, SUFFIXES.len() as i32);
            assert_eq!(tribe_rng.next_id(), *want, "tribe {i}");
        }
    }
}
